# Configurations for image processing

object_name: "M1" 

data_paths:
  bias_frames: 'data/photo/offsets/'
  dark_frames: 'data/photo/dark/'
  flat_frames: 'data/photo/flats/'
  science_images: 'data/photo/M1/'

filters_to_process:
  - B
  - R
  - V
  - Halpha
  - OIII

process_dark_frames: True

output_dirs:
  base_output_dir: 'output'
  reduced_dir: 'output/reduced'
  aligned_dir: 'output/aligned'
  stacked_dir: 'output/stacked'

color_combinations:
  - R: 'R'
    G: 'V'
    B: 'B'
  - R: 'Halpha'
    G: 'V'
    B: 'OIII'