# Configurations for image processing

object_name: "SH2_257" 

data_paths:
  bias_frames: 'data/photo/offsets/'
  dark_frames: 'data/photo/dark/'
  flat_frames: 'data/photo/flats/'
  science_images: 'data/photo/SH2_257/'

filters_to_process:
  - V
  - R
  - Halpha

process_dark_frames: True

output_dirs:
  base_output_dir: 'output'
  reduced_dir: 'output/reduced'
  aligned_dir: 'output/aligned'
  stacked_dir: 'output/stacked'

color_combinations:
  - R: 'Halpha'
    G: 'R'
    B: 'V'